#!/bin/bash
PASSWORD=$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c 32 | xargs)
PHPMAJOR=$(php  -r 'echo phpversion();' |  cut -d'.' -f1)
PHPMINOR=$(php  -r 'echo phpversion();' |  cut -d'.' -f2)

cd /usr/share/churchcrm/
ln -sf ChurchCRM-{{VERSION}} /usr/share/churchcrm/current
mv /usr/share/churchcrm/current/Include/Config.php.example /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|DB_SERVER_NAME\|\|#localhost#g /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|DB_SERVER_PORT\|\|#'3306'#g /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|DB_USER\|\|#'churchcrm'#g /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|DB_PASSWORD\|\|#${PASSWORD}#g /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|DB_NAME\|\|#'churchcrm'#g /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|DB_SERVER_NAME\|\|#'localhost'#g /usr/share/churchcrm/current/Include/Config.php.dpkg
sed -i s#\|\|ROOT_PATH\|\|##g /usr/share/churchcrm/current/Include/Config.php.dpkg

cd /etc/nginx/sites-enabled
ln -sf ../sites-available/churchcrm.conf 99-churchcrm.conf
make-ssl-cert generate-default-snakeoil
usermod --append --groups ssl-cert www-data

mysql -e "CREATE DATABASE IF NOT EXISTS churchcrm;"
mysql -e "CREATE USER IF NOT EXISTS 'churchcrm'@'localhost' IDENTIFIED BY '${PASSWORD}';"
mysql -e "GRANT ALL ON churchcrm.* TO 'churchcrm'@'localhost' IDENTIFIED BY '${PASSWORD}';"

chown -R www-data:www-data /usr/share/churchcrm/current/*
find /usr/share/churchcrm/current/ -type f -exec chmod 0664 {} \;
find /usr/share/churchcrm/current/ -type d -exec chmod 0775 {} \;
chmod 0600 /usr/share/churchcrm/current/Include/Config.php

systemctl restart nginx php${PHPMAJOR}.${PHPMINOR}-fpm

echo -e "These is only an initial setup.\n\u1b[31mPlease modify \u1b[31;4m/etc/nginx/sites-available/churchcrm.conf\u1b[0m \u1b[31mto your personal needs.\u1b[0m"
echo -e "\u1b[32mConnect to ChurchCRM on https://Admin:changeme@localhost:4343\u1b[0m"
